spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9094
      group-id: HomeWork-kafka
      auto-offset-reset: latest
      key-deserializer: ru.mpei.util.CustomDeserializer
      value-deserializer: ru.mpei.util.CustomDeserializer

    producer:
      bootstrap-servers: localhost:9094
      value-serializer: ru.mpei.util.CustomSerializer
      key-serializer: ru.mpei.util.CustomSerializer

topic:
  name:
    producer: topic-test-1
    consumer: topic-test-1